apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/App-of-apps-argo-example/gitops-core.git'
    targetRevision: main
    path: helm-org-charts/general-service
    helm:
      valueFiles:
      - ../../environments/stage/microservice-b-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
